//namespace scope
(function( DMI, $, undefined ){

////////////////////////////////////////////////////////////////////////////
// ability icons
//
// maps an inspector property key to the game's ability icon and its proper
// name: key -> [icon file stem in images/abilities/, tooltip label].
//
// GENERATED - see the note in README-abilities.txt. Icons are the game's own,
// taken from the ability list at https://illwiki.com/dom5/unit-abilities .
// Keys with no icon there are rendered as text instead, which is why this
// table is deliberately partial.
////////////////////////////////////////////////////////////////////////////

DMI.abilityIcons = {
	'acidshield': ['acid_splash', 'Acid Splash'],
	'adept_research': ['adept_researcher', 'Adept Researcher'],
	'almostundead': ['part_undead_or_demon', 'Part Undead/demon'],
	'ambidextrous': ['ambidextrous', 'Ambidextrous'],
	'amphibian': ['amphibious', 'Amphibious'],
	'animal': ['animal', 'Animal'],
	'animalawe': ['animal_awe', 'Animal Awe'],
	'appetite': ['gluttony', 'Gluttony'],
	'aquatic': ['aquatic', 'Aquatic'],
	'assassin': ['assassin', 'Assassin'],
	'astralfetters': ['astral_fetters', 'Astral Fetters'],
	'autoblessed': ['blessed', 'Blessed'],
	'autodishealer': ['disease_healer', 'Disease Healer'],
	'autohealer': ['healer', 'Healer'],
	'awe': ['awe', 'Awe'],
	'banefireshield': ['banefire_shield', 'Banefire Shield'],
	'batstartsum1': ['summon_allies', 'Summon Allies'],
	'batstartsum2': ['summon_allies', 'Summon Allies'],
	'batstartsum3': ['summon_allies', 'Summon Allies'],
	'batstartsum4': ['summon_allies', 'Summon Allies'],
	'beartattoo': ['magic_bear_tattoo', 'Magic Bear Tattoo'],
	'beastmaster': ['beastmaster', 'Beastmaster'],
	'berserk': ['berserker', 'Berserker'],
	'blessbers': ['berserk_when_blessed', 'Berserk when Blessed'],
	'blind': ['blind', 'Blind'],
	'bloodvengeance': ['blood_vengeance', 'Blood Vengeance'],
	'bluntres': ['resist_blunt', 'Blunt Resistant'],
	'boartattoo': ['magic_boar_tattoo', 'Magic Boar Tattoo'],
	'bodyguard': ['bodyguard', 'Bodyguard'],
	'bonusspells': ['innate_spellcaster', 'Innate Spellcaster'],
	'bringeroffortune': ['bringer_of_fortune', 'Bringer of Fortune'],
	'bugreform': ['swarm_body', 'Swarm Body'],
	'carcasscollector': ['carcass_collector', 'Carcass Collector'],
	'castledef': ['castle_defence_bonus', 'Castle Defence Bonus'],
	'chaospower': ['chaos_power', 'Chaos Power'],
	'chaosrec': ['chaos_recruitment', 'Chaos Recruitment'],
	'cold': ['chill_aura', 'Chill Aura'],
	'coldblood': ['cold_blooded', 'Cold Blooded'],
	'coldpower': ['cold_power', 'Cold Power'],
	'coldres': ['resist_cold', 'Cold Resistant'],
	'combatcaster': ['combat_caster', 'Combat Caster'],
	'comslave': ['communion_slave', 'Communion Slave'],
	'curseluckshield': ['fateweaving', 'Fateweaving'],
	'damagerev': ['damage_reversal', 'Damage Reversal'],
	'darkpower': ['dark_power', 'Dark Power'],
	'darkvision': ['darkvision', 'Darkvision'],
	'deathcurse': ['death_curse', 'Death Curse'],
	'demon': ['demon', 'Demon'],
	'disbelieve': ['disbelieve', 'Disbelieve'],
	'divineins': ['divine_insights', 'Divine Insights'],
	'domimmortal': ['dominion_immortality', 'Dominion Immortality'],
	'douse': ['blood_searcher', 'Blood Searcher'],
	'elegist': ['elegist', 'Elegist'],
	'ethereal': ['ethereal', 'Ethereal'],
	'ethtrue': ['true_ethereal', 'True Ethereal'],
	'exhaustion': ['exhaustion', 'Exhaustion'],
	'fear': ['fear', 'Fear'],
	'firepower': ['fire_power', 'Fire Power'],
	'fireres': ['resist_fire', 'Fire Resistant'],
	'fireshield': ['fire_shield', 'Fire Shield'],
	'fixforgebonus': ['forge_bonus', 'Forge Bonus'],
	'float': ['floating', 'Floating'],
	'flying': ['flying', 'Flying'],
	'forestsurvival': ['forest_survival', 'Forest Survival'],
	'forgebonus': ['forge_bonus', 'Forge Bonus'],
	'formationfighter': ['formation_fighter', 'Formation Fighter'],
	'gemprod': ['gem_generator', 'Gem Generator'],
	'giftofwater': ['water_breathing', 'Gift of Water Breathing'],
	'glamour': ['glamour', 'Glamour'],
	'haltheretic': ['halt_heretic', 'Halt Heretic'],
	'heal': ['recuperation', 'Recuperation'],
	'heat': ['heat_aura', 'Heat Aura'],
	'heretic': ['heretic', 'Heretic'],
	'holycost': ['sacred_2', 'Sacred (double holy cost)'],
	'holy': ['sacred', 'Sacred'],
	'homesick': ['homesickness', 'Homesickness'],
	'horrormarked': ['horror_mark', 'Horror Mark'],
	'horsetattoo': ['magic_horse_tattoo', 'Magic Horse Tattoo'],
	'iceforging': ['ice_forging', 'Ice Forging'],
	'iceprot': ['ice_protection', 'Ice Protection'],
	'immortal': ['immortal', 'Immortal'],
	'inanimate': ['inanimate', 'Inanimate'],
	'incprovdef': ['defence_organizer', 'Defence Organizer'],
	'incunrest': ['cause_unrest', 'Cause Unrest'],
	'inept_research': ['inept_researcher', 'Inept Researcher'],
	'inquisitor': ['inquisitor', 'Inquisitor'],
	'insane': ['insane', 'Insane'],
	'inspirational': ['inspirational', 'Inspirational'],
	'invisible': ['invisible', 'Invisible'],
	'invulnerable': ['invulnerability', 'Invulnerability'],
	'ironvul': ['iron_vulnerablity', 'Iron Vulnerability'],
	'isold': ['old_age', 'Old Age'],
	'ivylord': ['ivy_lord', 'Ivy Lord'],
	'leper': ['reaper', 'Reaper'],
	'magicbeing': ['magic_being', 'Magic Being'],
	'magicpower': ['magic_power', 'Magic Power'],
	'magicstudy': ['magically_attuned_researcher', 'Magically Attuned Researcher'],
	'makepearls': ['pearl_cultivator', 'Pearl Cultivator'],
	'mason': ['mason', 'Mason'],
	'mastersmith': ['master_smith', 'Master Smith'],
	'mind': ['mindless', 'Mindless'],
	'mindslime': ['mind_slimer', 'Mind Slimer'],
	'mountainrec': ['mountain_recruitment', 'Mountain Recruitment'],
	'mountainsurvival': ['mountain_survival', 'Mountain Survival'],
	'mummify': ['mummify', 'Mummify'],
	'neednoteat': ['need_not_eat', 'Need Not Eat'],
	'nobadevents': ['fortune_teller', 'Fortune Teller'],
	'noheal': ['never_heals', 'Never Heals'],
	'nohof': ['experience', 'Experience'],
	'noriverpass': ['cannot_pass_rivers', 'Cannot Pass Rivers'],
	'onebattlespell': ['innate_spellcaster', 'Innate Spellcaster'],
	'overcharged': ['overcharged', 'Overcharged'],
	'patience': ['assassin', 'Assassin'],		//"patience" is the assassin ability
	'patrolbonus': ['patrol_bonus', 'Patrol Bonus'],
	'petrify': ['petrification', 'Petrification'],
	'pierceres': ['resist_pierce', 'Pierce Resistant'],
	'pillagebonus': ['pillager', 'Pillager'],
	'plaguedoctor': ['plague_doctor', 'Plague Doctor'],
	'poisonarmor': ['poison_barbs', 'Poison Barbs'],
	'poisoncloud': ['poison_cloud', 'Poison Cloud'],
	'poisonres': ['resist_poison', 'Poison Resistant'],
	'poisonskin': ['poisonous_skin', 'Poisonous Skin'],
	'polyimmune': ['polymorph_immunity', 'Polymorph Immunity'],
	'pooramphibian': ['poor_amphibian', 'Poor Amphibian'],
	'popkill': ['population_killer', 'Population Killer'],
	'prophetshape': ['prophet', 'Prophet'],
	'reanimator': ['reanimator', 'Reanimator'],
	'reanimpriest': ['reanimator_priest', 'Reanimator Priest'],
	'regeneration': ['regeneration', 'Regeneration'],
	'reincarnation': ['reincarnation', 'Reincarnation'],
	'reinvigoration': ['reinvigoration', 'Reinvigoration'],
	'resources': ['resource_bonus', 'Provides Resources'],
	'saltvul': ['salt_vulnerability', 'Salt Vulnerability'],
	'scalewalls': ['scale_walls', 'Scale Walls'],
	'seduce': ['seduction', 'Seduction'],
	'shapechange': ['shapechanger', 'Shape Changer'],
	'shatteredsoul': ['shattered_soul', 'Shattered Soul'],
	'shockres': ['resist_shock', 'Shock Resistant'],
	'siegebonus': ['siege_bonus', 'Siege Bonus'],
	'skilledrider': ['skilled_rider', 'Skilled Rider'],
	'skirmisher': ['skirmisher', 'Skirmisher'],
	'sleepaura': ['sleep_cloud', 'Sleep Aura'],
	'smartmount': ['smart_mount', 'Smart Mount'],
	'slashres': ['resist_slash', 'Slash Resistant'],
	'slave': ['slave', 'Slave'],
	'slaver': ['slaver', 'Slaver'],
	'slimer': ['slimer', 'Slimer'],
	'snaketattoo': ['magic_snake_tattoo', 'Magic Snake Tattoo'],
	'snowmove': ['snow_move', 'Snow Move'],
	'spellsinger': ['spell_singer', 'Spell Singer'],
	'spiritform': ['spiritform', 'Spirit Form'],	//the Ancestral Spirit's own sprite
	'spiritsight': ['spirit_sight', 'Spirit Sight'],
	'spreaddeath': ['spreads_death', 'Spreads Death'],
	'spreaddom': ['spreads_dominion', 'Spreads Dominion'],
	'spreadgrowth': ['spreads_growth', 'Spreads Growth'],
	'spreadorder': ['spreads_order', 'Spreads Order'],
	'spy': ['spy', 'Spy'],
	'standard': ['standard', 'Standard'],
	'startaff': ['affliction', 'Affliction'],
	'startingaff': ['affliction', 'Affliction'],
	'stealthy': ['stealth', 'Stealthy'],
	'stormimmune': ['storm_immunity', 'Storm Immunity'],
	'stormpower': ['storm_power', 'Storm Power'],
	'stunimmunity': ['stun_immunity', 'Stun Immunity'],
	'stupid': ['stupid', 'Stupid'],
	'stygianguide': ['stygian_guide', 'Stygian Guide'],
	'succubus': ['seduction', 'Seduction'],
	'summon': ['summon_allies', 'Summon Allies'],
	'summon5': ['summon_allies', 'Summon Allies'],
	'sunawe': ['sun_awe', 'Sun Awe'],
	'supplybonus': ['supply_bonus', 'Supply Bonus'],
	'swampsurvival': ['swamp_survival', 'Swamp Survival'],
	'swimming': ['swimming', 'Swimming'],
	'taskmaster': ['taskmaster', 'Taskmaster'],
	'teleport': ['teleport', 'Teleport'],
	'trample': ['trample', 'Trample'],
	'trampswallow': ['swallow_on_trample', 'Swallow on Trample'],
	'twiceborn': ['twiceborn', 'Twiceborn'],
	'undead': ['undead', 'Undead'],
	'undisciplined': ['undisciplined', 'Undisciplined'],
	'unseen': ['unseen', 'Unseen'],
	'unsurr': ['unsurroundable', 'Unsurroundable'],
	'unteleportable': ['teleport', 'Teleport'],
	'uwregen': ['uw_regeneration', 'UW Regeneration'],
	'verystupid': ['stupid', 'Stupid'],
	'voidsanity': ['void_sanity', 'Void Sanity'],
	'wastesurvival': ['wasteland_survival', 'Wasteland Survival'],
	'waterbreathing': ['water_breathing', 'Water Breathing'],
	'wolftattoo': ['magic_wolf_tattoo', 'Magic Wolf Tattoo'],
	'woundfend': ['affliction_resistance', 'Affliction Resistance'],
	'yearturn': ['power_of_the_turning_year', 'Power of the Turning Year'],
};

DMI.abilityIconPath = 'images/abilities/';

//namespace args
}( window.DMI = window.DMI || {}, jQuery ));
